# .travis.yml
language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deployLibraryToNPM
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release