# .travis.yml
language: node_js
node_js:
  - 12

jobs:
  include:
    - stage: test
      script: npm run test
    - stage: deployLibraryToNPM
      node_js: lts/*
      script: npm run build
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
    - stage: deployDemoSiteToGitHubPage
      script: npm run build-demo-site
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: ${GITHUB_TOKEN}
        keep_history: true
        local_dir: demoSite
